# Generated by Django 5.2.11 on 2026-03-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_smtpcredential_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpcredential',
            name='from_name',
            field=models.CharField(blank=True, help_text='e.g. Cristina from LeadNexus', max_length=255, null=True),
        ),
    ]
