# Generated by Django 5.2.11 on 2026-03-01 20:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_smtpcredential_from_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpcredential',
            name='daily_limit',
            field=models.IntegerField(default=50, help_text='Max emails per 24h'),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='emails_sent_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='last_reset_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
