# Generated by Django 5.2.11 on 2026-02-23 19:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niche', models.CharField(help_text='Search niche / keywords', max_length=500)),
                ('max_profiles', models.PositiveIntegerField(default=50, help_text='Max profiles to scrape')),
                ('scrape_websites', models.BooleanField(default=True, help_text='Also visit & scrape company websites')),
                ('headless', models.BooleanField(default=False, help_text='Run Chrome in headless mode')),
                ('linkedin_email', models.CharField(blank=True, default='', max_length=255)),
                ('linkedin_password', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('progress', models.PositiveIntegerField(default=0, help_text='Profiles scraped so far')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'LinkedIn Scrape Job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Target website URL', max_length=2000)),
                ('scrape_contact', models.BooleanField(default=True, help_text='Also scrape contact/about pages')),
                ('max_contact_pages', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website Scrape Job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedLinkedInProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.URLField(max_length=2000)),
                ('name', models.CharField(blank=True, default='N/A', max_length=500)),
                ('headline', models.TextField(blank=True, default='N/A')),
                ('location', models.CharField(blank=True, default='N/A', max_length=500)),
                ('about', models.TextField(blank=True, default='N/A')),
                ('company_size', models.CharField(blank=True, default='N/A', max_length=200)),
                ('company_type', models.CharField(blank=True, default='N/A', max_length=200)),
                ('industry', models.CharField(blank=True, default='N/A', max_length=300)),
                ('founded', models.CharField(blank=True, default='N/A', max_length=100)),
                ('website', models.URLField(blank=True, max_length=2000, null=True)),
                ('website_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website_address', models.TextField(blank=True, null=True)),
                ('website_facebook', models.URLField(blank=True, null=True)),
                ('website_twitter', models.URLField(blank=True, null=True)),
                ('website_instagram', models.URLField(blank=True, null=True)),
                ('website_linkedin', models.URLField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.linkedinscrapejob')),
            ],
            options={
                'verbose_name': 'Scraped LinkedIn Profile',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(max_length=2000)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('pages_scraped', models.JSONField(blank=True, default=list)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.scrapejob')),
            ],
            options={
                'verbose_name': 'Scraped Website',
            },
        ),
    ]
