# Generated by Django 5.2.4 on 2026-03-07 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_linkedinscrapejob_linkedin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the job (e.g., Bulk Upload CSV)', max_length=255),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='urls_to_scrape',
            field=models.JSONField(blank=True, default=list, help_text='List of URLs for bulk scraping'),
        ),
        migrations.AlterField(
            model_name='scrapedwebsite',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.scrapejob'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='url',
            field=models.URLField(blank=True, help_text='Target website URL', max_length=2000, null=True),
        ),
    ]
