# Generated by Django 5.2.4 on 2026-03-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scrapejob_name_scrapejob_urls_to_scrape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinscrapejob',
            name='company_size',
            field=models.CharField(blank=True, default='', help_text='Filter by company size (e.g., 51-200 employees)', max_length=100),
        ),
        migrations.AddField(
            model_name='linkedinscrapejob',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Filter by location (e.g., London, USA)', max_length=255),
        ),
    ]
