# Generated by Django 5.2.4 on 2026-03-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_linkedinscrapejob_user_scrapejob_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrations_enabled', models.BooleanField(default=True, help_text='If disabled, new users cannot register accounts.')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='If enabled, shows a maintenance notice.')),
            ],
            options={
                'verbose_name': 'Global System Setting',
                'verbose_name_plural': 'Global System Settings',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes regarding this user (payments, etc)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership_status',
            field=models.CharField(choices=[('free', 'Free Operative'), ('pro', 'Pro Operative'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
