# Generated by Django 5.2.4 on 2026-03-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_globalsettings_userprofile_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_limit_daily',
            field=models.PositiveIntegerField(default=5, help_text='Max website scrape jobs per 24h'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='jobs_today_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_action_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_limit_daily',
            field=models.PositiveIntegerField(default=2, help_text='Max LinkedIn scrape jobs per 24h'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_records_scraped',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
