# Generated by Django 5.2.4 on 2026-03-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_job_limit_daily_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_outreach_limit_daily',
            field=models.PositiveIntegerField(default=50, help_text='Max emails sent per 24h'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emails_today_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smtp_limit',
            field=models.PositiveIntegerField(default=2, help_text='Max SMTP accounts allowed'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_emails_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_linkedin_scraped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_websites_scraped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_records_scraped',
            field=models.PositiveIntegerField(default=0, help_text='Total verified contacts found across all origins'),
        ),
    ]
