# Generated by Django 5.2.4 on 2026-03-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_email_outreach_limit_daily_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_today_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
