# Generated by Django 5.2.4 on 2026-03-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_linkedin_today_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='emails_today_count',
            new_name='emails_this_month_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_outreach_limit_daily',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_outreach_limit_monthly',
            field=models.PositiveIntegerField(default=1000, help_text='Max emails sent per month'),
        ),
    ]
