# Generated by Django 5.2.4 on 2026-03-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_emails_today_count_userprofile_emails_this_month_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='jobs_today_count',
            new_name='jobs_this_month_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='linkedin_today_count',
            new_name='linkedin_this_month_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='job_limit_daily',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin_limit_daily',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_limit_monthly',
            field=models.PositiveIntegerField(default=150, help_text='Max website scrape jobs per month'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_limit_monthly',
            field=models.PositiveIntegerField(default=60, help_text='Max LinkedIn scrape jobs per month'),
        ),
    ]
