# Generated by Django 5.2.4 on 2026-03-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_jobs_today_count_userprofile_jobs_this_month_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='True if user has an active paid subscription'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes regarding this user (billing, support, etc)'),
        ),
    ]
