# Generated by Django 5.2.4 on 2026-03-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofile_is_paid_userprofile_last_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='contact_email',
            field=models.EmailField(default='sales@leadnexus.ai', help_text='Public contact email displayed on the landing page.', max_length=254),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='whatsapp_number',
            field=models.CharField(default='+1234567890', help_text='WhatsApp number with country code (e.g. +1234567890) for the chat button.', max_length=20),
        ),
    ]
