# Generated by Django 5.2.4 on 2026-03-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_globalsettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_outreach_limit_monthly',
            field=models.PositiveIntegerField(default=100, help_text='Max individual emails sent per month'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emails_this_month_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Emails Sent This Month'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_limit_monthly',
            field=models.PositiveIntegerField(default=100, help_text='Max domains scanned per month'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='jobs_this_month_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Domains Scanned This Month'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_limit_monthly',
            field=models.PositiveIntegerField(default=0, help_text='Max LinkedIn profiles scraped per month'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_this_month_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Profiles Scraped This Month'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='smtp_limit',
            field=models.PositiveIntegerField(default=1, help_text='Max SMTP accounts allowed'),
        ),
    ]
