# Generated by Django 5.2.4 on 2026-03-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_userprofile_email_outreach_limit_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='mrr_target',
            field=models.DecimalField(decimal_places=2, default=55000.0, help_text='Monthly Revenue target for the dashboard.', max_digits=12),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='registrations_target',
            field=models.PositiveIntegerField(default=1000, help_text='Monthly New Registrations target for the dashboard.'),
        ),
    ]
