# Generated by Django 5.2.4 on 2026-03-15 15:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_globalsettings_mrr_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niche', models.CharField(help_text='Search niche / keywords', max_length=500)),
                ('max_results', models.PositiveIntegerField(default=50, help_text='Max websites to find and scrape')),
                ('scrape_contact', models.BooleanField(default=True, help_text='Also scrape contact/about pages')),
                ('max_contact_pages', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('progress', models.PositiveIntegerField(default=0, help_text='Websites scraped so far')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Keyword Scrape Job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedKeywordWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(max_length=2000)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('pages_scraped', models.JSONField(blank=True, default=list)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.keywordscrapejob')),
            ],
            options={
                'verbose_name': 'Scraped Keyword Website',
            },
        ),
    ]
