# Generated by Django 5.2.4 on 2026-03-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_keywordscrapejob_scrapedkeywordwebsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordscrapejob',
            name='max_contact_pages',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='max_contact_pages',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
