# Generated by Django 5.2.4 on 2026-03-19 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_keywordscrapejob_max_contact_pages_and_more'),
        ('mail', '0010_recipient_smtp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='contact_notification_email',
            field=models.EmailField(default='admin@leadnexus.ai', help_text='Email where notifications for new contact requests will be sent.', max_length=254),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='contact_notification_smtp',
            field=models.ForeignKey(blank=True, help_text='The SMTP account to use for sending these specific system notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.smtpcredential'),
        ),
    ]
