# Generated by Django 5.2.4 on 2026-03-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_globalsettings_contact_notification_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='contact_notification_email',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='contact_notification_smtp',
        ),
    ]
