# Generated by Django 5.2.4 on 2026-03-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_globalsettings_contact_notification_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_sent_80_percent_alert',
            field=models.BooleanField(default=False, help_text='Prevents duplicate quota alerts in the same month'),
        ),
    ]
