# Generated by Django 5.2.4 on 2026-03-20 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_userprofile_has_sent_80_percent_alert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalSettings',
        ),
    ]
