# Generated by Django 4.2.29 on 2026-03-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_delete_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tracking_domain',
            field=models.CharField(blank=True, help_text='Custom domain for tracking pixel (e.g., link.yourdomain.com)', max_length=255, null=True),
        ),
    ]
