# Generated by Django 4.2.29 on 2026-03-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userprofile_tracking_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_send_window_end',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_send_window_start',
            field=models.TimeField(blank=True, default='09:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_work_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
