# Generated by Django 4.2.29 on 2026-03-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_userprofile_default_send_window_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_websites_per_search',
            field=models.PositiveIntegerField(default=100, help_text='Max websites allowed per single search job'),
        ),
    ]
