# Generated by Django 4.2.29 on 2026-03-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_userprofile_max_websites_per_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.CharField(blank=True, help_text='Affiliate referral code used during signup', max_length=20, null=True),
        ),
    ]
