# Generated by Django 4.2.29 on 2026-04-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_userprofile_plan_alter_userprofile_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedkeywordwebsite',
            name='email',
            field=models.TextField(blank=True, help_text='Comma-separated verified emails', null=True),
        ),
        migrations.AlterField(
            model_name='scrapedlinkedinprofile',
            name='website_email',
            field=models.TextField(blank=True, help_text='Comma-separated verified emails', null=True),
        ),
        migrations.AlterField(
            model_name='scrapedwebsite',
            name='email',
            field=models.TextField(blank=True, help_text='Comma-separated verified emails', null=True),
        ),
    ]
