# Generated by Django 5.2.4 on 2026-03-19 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
        ('mail', '0010_recipient_smtp_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.EmailField(default='admin@leadnexus.ai', help_text='Email where notifications for new contact requests will be sent.', max_length=254)),
                ('notification_smtp', models.ForeignKey(blank=True, help_text='The SMTP account to use for sending these specific system notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.smtpcredential')),
            ],
            options={
                'verbose_name': 'Contact System Setting',
                'verbose_name_plural': 'Contact System Settings',
            },
        ),
    ]
