# Generated by Django 5.2.4 on 2026-03-20 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTaskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_bot_token', models.CharField(blank=True, help_text='Bot token for admin notifications.', max_length=255, null=True)),
                ('admin_chat_id', models.CharField(blank=True, help_text='Telegram Chat ID for receiving alerts.', max_length=255, null=True)),
                ('enable_error_alerts', models.BooleanField(default=False, help_text='If enabled, sends telegram alerts on critical errors.')),
            ],
            options={
                'verbose_name': 'Admin Intelligence Setting',
                'verbose_name_plural': 'Admin Intelligence Settings',
            },
        ),
        migrations.CreateModel(
            name='ErrorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('campaign_fail', 'Campaign Failure'), ('server_error', '500 Server Error'), ('security_breach', 'Security Alert'), ('quota_exhausted', 'Quota Exhaustion')], max_length=20)),
                ('message', models.TextField()),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('sent_to_telegram', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ServerPerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('latency_seconds', models.FloatField()),
                ('status_code', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
