# Generated by Django 5.2.4 on 2026-03-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintasksettings',
            name='enable_performance_logging',
            field=models.BooleanField(default=True, help_text='Record system-wide latency.'),
        ),
        migrations.AddField(
            model_name='admintasksettings',
            name='retention_days',
            field=models.PositiveIntegerField(default=7, help_text='Automatically delete logs older than this number of days.'),
        ),
        migrations.AddField(
            model_name='admintasksettings',
            name='slow_request_threshold',
            field=models.FloatField(default=0.5, help_text='Only log requests that take longer than this (in seconds). Set to 0 to log everything.'),
        ),
        migrations.AlterField(
            model_name='serverperformancelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
