# Generated by Django 5.2.4 on 2026-03-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintask', '0002_admintasksettings_enable_performance_logging_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrations_enabled', models.BooleanField(default=True, help_text='If disabled, new users cannot register accounts.')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='If enabled, shows a maintenance notice.')),
                ('contact_email', models.EmailField(default='sales@leadnexus.ai', help_text='Public contact email displayed on the landing page.', max_length=254)),
                ('whatsapp_number', models.CharField(default='+1234567890', help_text='WhatsApp number with country code (e.g. +1234567890) for the chat button.', max_length=20)),
                ('mrr_target', models.DecimalField(decimal_places=2, default=55000.0, help_text='Monthly Revenue target for the dashboard.', max_digits=12)),
                ('registrations_target', models.PositiveIntegerField(default=1000, help_text='Monthly New Registrations target for the dashboard.')),
            ],
            options={
                'verbose_name': 'Global System Setting',
                'verbose_name_plural': 'Global System Settings',
            },
        ),
    ]
