# Generated by Django 4.2.29 on 2026-03-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintask', '0003_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='annual_discount_percentage',
            field=models.PositiveIntegerField(default=20, help_text="Percentage discount shown on the annual billing switch (e.g. 20 for 'SAVE 20%')."),
        ),
    ]
