# Generated by Django 4.2.29 on 2026-03-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintask', '0004_globalsettings_annual_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL.', null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL.', null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn page URL.', null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='twitter_x_url',
            field=models.URLField(blank=True, help_text='X (Twitter) profile URL.', null=True),
        ),
    ]
