# Generated by Django 4.2.11 on 2026-05-10 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mail', '0017_alter_emailcampaign_add_unsubscribe_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarmupAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inactive', 'Not Started'), ('warming', 'Warming Up'), ('warmed', 'Fully Warmed'), ('paused', 'Paused')], default='inactive', max_length=20)),
                ('day_number', models.IntegerField(default=0, help_text='Current warmup day')),
                ('target_days', models.IntegerField(default=30, help_text='Total days to warm up')),
                ('current_daily_volume', models.IntegerField(default=3)),
                ('max_daily_volume', models.IntegerField(default=50, help_text='Max emails/day at full warmup')),
                ('total_sent', models.IntegerField(default=0)),
                ('inbox_count', models.IntegerField(default=0)),
                ('spam_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('warmup_score', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('smtp_credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_profile', to='mail.smtpcredential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WarmupEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.CharField(choices=[('unknown', 'Not Checked Yet'), ('inbox', 'Landed in Inbox ✅'), ('spam', 'Went to Spam ⚠️')], default='unknown', max_length=10)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('is_replied', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_emails', to='warmup.warmupaccount')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='WarmupPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('imap_host', models.CharField(blank=True, help_text='Leave blank to auto-detect', max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=500)),
                ('use_tls', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_pool', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'email')},
            },
        ),
        migrations.CreateModel(
            name='WarmupDailyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_number', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('inbox_rate', models.FloatField(default=0)),
                ('spam_rate', models.FloatField(default=0)),
                ('reply_rate', models.FloatField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to='warmup.warmupaccount')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('account', 'date')},
            },
        ),
    ]
