# Generated by Django 5.2.4 on 2026-03-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Web Scrape Jobs / mo'", max_length=200)),
                ('free_value', models.CharField(help_text="e.g. '150' or 'yes' or 'no'", max_length=100)),
                ('pro_value', models.CharField(help_text="e.g. '1000' or 'yes' or 'no'", max_length=100)),
                ('enterprise_value', models.CharField(help_text="e.g. 'Unlimited' or 'yes' or 'no'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which it appears in the table')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
