# Generated by Django 5.2.4 on 2026-03-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'INITIATE', 'PROFESSIONAL'", max_length=100)),
                ('badge', models.CharField(blank=True, help_text="e.g. 'MOST POWERFUL'", max_length=100, null=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per month when billed annually', max_digits=10, null=True)),
                ('is_custom_pricing', models.BooleanField(default=False, help_text='Check if price should just say CUSTOM')),
                ('features', models.TextField(help_text='Enter one feature per line')),
                ('btn_text', models.CharField(default='Initiate Growth', max_length=100)),
                ('btn_url_name', models.CharField(default='login', max_length=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlights the card and makes it larger')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
