# Generated by Django 4.2.29 on 2026-03-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='short_description',
            field=models.CharField(blank=True, default='For growing teams', help_text='Text below the price', max_length=200, null=True),
        ),
    ]
