# Generated by Django 5.2.11 on 2026-02-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='name',
            field=models.CharField(default='Untitled Campaign', help_text='A friendly name for your campaign', max_length=255),
        ),
    ]
