# Generated by Django 5.2.11 on 2026-03-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_emailcampaign_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpcredential',
            name='provider',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook/Hotmail'), ('google_workspace', 'Google Workspace'), ('microsoft_365', 'Microsoft 365'), ('custom', 'Custom SMTP')], default='custom', max_length=50),
        ),
    ]
