# Generated by Django 5.2.4 on 2026-03-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_smtpcredential_daily_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='open_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipient',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipient',
            name='open_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipient',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
