# Generated by Django 5.2.4 on 2026-03-14 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_emailcampaign_user_smtpcredential_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='sent_at',
            new_name='last_sent_at',
        ),
        migrations.AddField(
            model_name='recipient',
            name='current_step_index',
            field=models.IntegerField(default=0, help_text='Last successfully sent step number'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipient',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('replied', 'Replied'), ('completed', 'Completed'), ('failed', 'Failed'), ('unsubscribed', 'Unsubscribed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CampaignStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=1, help_text='1 for first mail, 2 for first follow-up, etc.')),
                ('wait_days', models.IntegerField(default=3, help_text='Days to wait after previous step')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Template body. Supports {{ name }}')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='mail.emailcampaign')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('campaign', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='SentEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body_sent', models.TextField()),
                ('message_id', models.CharField(db_index=True, help_text='SMTP Message-ID for reply threading', max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='mail.recipient')),
                ('smtp_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.smtpcredential')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.campaignstep')),
            ],
        ),
    ]
