# Generated by Django 5.2.4 on 2026-03-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_rename_sent_at_recipient_last_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='gap_minutes',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='gap_seconds',
            field=models.IntegerField(default=2, help_text='Wait time between each email (seconds)'),
        ),
    ]
