# Generated by Django 5.2.4 on 2026-03-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_remove_emailcampaign_gap_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='smtp_email',
            field=models.EmailField(blank=True, help_text='SMTP email used for last send', max_length=254, null=True),
        ),
    ]
