# Generated by Django 4.2.29 on 2026-03-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_recipient_smtp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='reply_count',
            field=models.IntegerField(default=0, help_text='Total recipients who have replied'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='current_step_index',
            field=models.IntegerField(db_index=True, default=0, help_text='Last successfully sent step number'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='is_opened',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='is_replied',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('replied', 'Replied'), ('completed', 'Completed'), ('failed', 'Failed'), ('unsubscribed', 'Unsubscribed')], db_index=True, default='pending', max_length=20),
        ),
    ]
