# Generated by Django 4.2.29 on 2026-03-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_emailcampaign_reply_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set a time to start this campaign automatically', null=True),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
