# Generated by Django 4.2.29 on 2026-03-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0012_emailcampaign_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstep',
            name='body_b',
            field=models.TextField(blank=True, help_text='Alternate body for A/B testing', null=True),
        ),
        migrations.AddField(
            model_name='campaignstep',
            name='subject_b',
            field=models.CharField(blank=True, help_text='Alternate subject for A/B testing', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='send_window_end',
            field=models.TimeField(blank=True, help_text='Ending hour (e.g., 17:00)', null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='send_window_start',
            field=models.TimeField(blank=True, help_text='Starting hour (e.g., 09:00)', null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='work_days',
            field=models.CharField(default='1,2,3,4,5', help_text='Comma separated days (1=Mon, 7=Sun)', max_length=20),
        ),
        migrations.AddField(
            model_name='recipient',
            name='is_unsubscribed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='recipient',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentemaillog',
            name='variant_used',
            field=models.CharField(default='A', help_text='A or B variant used for this send', max_length=1),
        ),
    ]
