# Generated by Django 4.2.29 on 2026-04-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0013_campaignstep_body_b_campaignstep_subject_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstep',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='step_attachments/'),
        ),
        migrations.AddField(
            model_name='campaignstep',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='campaign_attachments/'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('replied', 'Replied'), ('completed', 'Completed'), ('failed', 'Failed'), ('unsubscribed', 'Unsubscribed'), ('sending', 'Sending...')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='recipient',
            unique_together={('campaign', 'email')},
        ),
    ]
