# Generated by Django 4.2.29 on 2026-05-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0014_campaignstep_attachment_campaignstep_attachment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpcredential',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='auth_type',
            field=models.CharField(choices=[('smtp', 'SMTP / App Password'), ('oauth', 'Gmail API (OAuth2)')], default='smtp', max_length=20),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='scopes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpcredential',
            name='token_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smtpcredential',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smtpcredential',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smtpcredential',
            name='port',
            field=models.IntegerField(blank=True, default=587, null=True),
        ),
        migrations.AlterField(
            model_name='smtpcredential',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
