# Generated by Django 4.2.11 on 2026-05-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0015_smtpcredential_access_token_smtpcredential_auth_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='add_unsubscribe_link',
            field=models.BooleanField(default=True, help_text='Add a one-click unsubscribe link to the footer.'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='track_opens',
            field=models.BooleanField(default=True, help_text='Embed an invisible tracking pixel to track email opens.'),
        ),
    ]
