# Generated by Django 4.2.11 on 2026-05-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0016_emailcampaign_add_unsubscribe_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='add_unsubscribe_link',
            field=models.BooleanField(default=False, help_text='Add a one-click unsubscribe link to the footer.'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='gap_seconds',
            field=models.IntegerField(default=120, help_text='Wait time between each email (seconds). Minimum 90s recommended for cold outreach.'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='track_opens',
            field=models.BooleanField(default=False, help_text='Embed an invisible tracking pixel to track email opens. WARNING: Only enable if your tracking domain matches your sending domain to avoid spam penalties.'),
        ),
    ]
