# Generated by Django 5.2.11 on 2026-02-28 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinscrapejob',
            name='linkedin_email',
            field=models.CharField(blank=True, default='', help_text='Manual email (overridden if account selected)', max_length=255),
        ),
        migrations.AlterField(
            model_name='linkedinscrapejob',
            name='linkedin_password',
            field=models.CharField(blank=True, default='', help_text='Manual password (overridden if account selected)', max_length=255),
        ),
        migrations.CreateModel(
            name='LinkedInAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, help_text='Optional nickname for this account', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is currently usable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LinkedIn Account',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='linkedinscrapejob',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Stored LinkedIn account to use for this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.linkedinaccount'),
        ),
    ]
