# Generated by Django 4.2.29 on 2026-03-27 16:25

import affiliatemarketing.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(default=affiliatemarketing.models.generate_referral_code, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('payout_method', models.CharField(choices=[('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('crypto', 'Cryptocurrency')], default='paypal', max_length=20)),
                ('payout_email', models.EmailField(blank=True, help_text='PayPal email or bank contact', max_length=254, null=True)),
                ('payout_details', models.TextField(blank=True, help_text='Bank account or crypto wallet details', null=True)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_signups', models.PositiveIntegerField(default=0)),
                ('total_paid_conversions', models.PositiveIntegerField(default=0)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affiliate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Affiliate commission % of the plan price (e.g. 20 = 20%)', max_digits=5)),
                ('referral_discount_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Discount % off plan price for users referred by an affiliate (e.g. 10 = 10%)', max_digits=5)),
                ('auto_approve_affiliates', models.BooleanField(default=True, help_text='If True, affiliates are approved instantly on registration')),
                ('minimum_payout', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum balance required before affiliate can request a payout', max_digits=10)),
                ('cookie_duration_days', models.PositiveIntegerField(default=30, help_text='How many days the referral cookie/session is valid')),
            ],
            options={
                'verbose_name': 'Affiliate Program Settings',
                'verbose_name_plural': 'Affiliate Program Settings',
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payout_method', models.CharField(max_length=20)),
                ('payout_details', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='affiliatemarketing.affiliate')),
            ],
            options={
                'verbose_name': 'Payout Request',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='Pro', max_length=100)),
                ('plan_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='affiliatemarketing.affiliate')),
                ('referred_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affiliate Earning',
                'ordering': ['-created_at'],
            },
        ),
    ]
