# Generated by Django 4.2.29 on 2026-03-27 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiliatemarketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliate',
            old_name='pending_balance',
            new_name='total_revenue',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='payout_details',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='payout_email',
        ),
        migrations.RemoveField(
            model_name='payoutrequest',
            name='payout_details',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='audience_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Encrypted bank account holder name', max_length=500),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Encrypted account number/IBAN', max_length=500),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Encrypted bank/branch name', max_length=500),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='bank_swift_code',
            field=models.CharField(blank=True, help_text='Encrypted SWIFT/BIC code (optional)', max_length=500),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='country',
            field=models.CharField(blank=True, default='Pakistan', max_length=100),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='easypaisa_name',
            field=models.CharField(blank=True, help_text='Encrypted EasyPaisa account holder name', max_length=500),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='easypaisa_number',
            field=models.CharField(blank=True, help_text='Encrypted EasyPaisa mobile number', max_length=500),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='paypal_email',
            field=models.CharField(blank=True, help_text='Encrypted PayPal email', max_length=500),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='promotion_method',
            field=models.CharField(choices=[('blog', 'Blog / Website'), ('youtube', 'YouTube Channel'), ('social', 'Social Media (Instagram/TikTok/X)'), ('newsletter', 'Newsletter / Email List'), ('agency', 'Agency / Consulting Firm'), ('community', 'Online Community / Forum'), ('other', 'Other')], default='blog', max_length=30),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_affiliates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='payout_snapshot',
            field=models.TextField(blank=True, help_text='Encrypted JSON snapshot of payout account details'),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='payout_method',
            field=models.CharField(choices=[('easypaisa', 'EasyPaisa (Pakistan)'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer')], default='easypaisa', max_length=20),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='status',
            field=models.CharField(choices=[('pending', 'Under Review'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='affiliatesettings',
            name='auto_approve_affiliates',
            field=models.BooleanField(default=False, help_text='If True, affiliates are approved instantly on registration'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='payout_method',
            field=models.CharField(default='easypaisa', max_length=20),
        ),
    ]
