# Generated by Django 4.2.29 on 2026-03-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliatemarketing', '0002_rename_pending_balance_affiliate_total_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='is_payout_verified',
            field=models.BooleanField(default=False, help_text='True if admin verified the payout details'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='PDF or image of the transfer receipt', null=True, upload_to='payout_receipts/'),
        ),
    ]
